preview: '@preview-unpadded'
context:
  options:
    - text: United States
      value: us
    - text: Germany
      value: de
    - text: France
      value: fr
    - text: India
      value: in
    - text: Japan
      value: jp
    - text: Spain
      value: es
variants:
  - name: Errors
    notes: An error summary can be shown at the top of the form.
  - name: Success
    notes: On a successful submission the form is hidden and a “thank you” message is shown in its place.
