context:
  label: Menu list
  default: default
  variants:
    - name: Download
      notes: Customized with mzp-t-download to display download icon on hover
      context:
        class: 'mzp-t-download'



