status: deprecated
context:
  title: A Headline With 30 Characters
  tagline: A short tagline.
  desc: A description of about 150 characters, give or take. That means we usually only have room for one or two sentences. Here is what that looks like.
  cta: Call to Action
  cta_link: https://example.com
variants:
  - name: With image
    notes: |
      Add the `mzp-has-image` class to change the layout for a hero image. The copy
      and image stack vertically on small screens and appear side by side on larger
      screens.

      Hero images can overflow their container, with part of one side hidden off-screen
      at some screen sizes. This is by design and this component was intended for decorative,
      editorial-style images not essential content. If you expect the entire hero image to
      be visible, this isn’t the right component to use. It’s one reason this component has
      been **deprecated in favor of the [Split component](/components/detail/split)**.

      - By default the copy is on the left and image on the right. Reverse the layout
        with an `mzp-l-reverse` class.
      - The image and copy switch sides in RTL languages. Plan for this and choose
        your image wisely.
      - The height of the hero section is determined by the amount of text within it.
        Long titles, long introductions, product logos, CTAs, etc all contribute to
        how much space the hero takes up.
      - Images are scaled to fit the height of the container, thus the size of the image
        is largely determined by the height of the hero section. Taller heroes (with more
        content) will have larger images and more of one side may be hidden off-screen,
        depending on the image width. Plan for this and choose your image wisely.
      - Page heroes are intended to span the entire viewport.

      ### Tips
      - We recommend hero images at least 800px by 600px. A 16:9 aspect ratio works well,
      though more of it can be hidden when the hero section is tall. Plan for this and
      choose your image wisely.
      - Choose your image wisely.
    context:
      tagline: False
      image: '/img/image-3-2.jpg'
  - name: With image, reversed
    notes: |
      By default the copy is on the left and image on the right. Reverse the layout
      with an `mzp-l-reverse` class. In a reverse layout the image can overflow to the
      left, hiding some of the image. Plan for this and choose your image wisely.

      The image and copy switch sides in RTL languages.

      The `mzp-l-reverse` class has no effect on a centered Hero (without an image).
    context:
      class: mzp-l-reverse
      tagline: False
      image: '/img/image-16-9.jpg'
  - name: Branded
    notes: |
      A product logo can be displayed using an additional theme class:
        - `mzp-t-product-firefox`
        - `mzp-t-product-beta`
        - `mzp-t-product-developer`
        - `mzp-t-product-nightly`
        - `mzp-t-product-focus`
        - `mzp-t-product-mozilla`
        - `mzp-t-product-vpn`
        - `mzp-t-product-pocket`
    context:
      class: mzp-t-product-firefox
      cta_class: mzp-t-product mzp-t-lg
  - name: Dark
    notes: |
      A dark theme is available with the `mzp-t-dark` theme class. This is example
      also features an image and brand logo.
    context:
      title: Dark theme branded hero with image
      tagline: Large tagline, no description.
      desc: False
      class: mzp-t-product-nightly mzp-t-dark
      image: '/img/image-3-2.jpg'
      cta_class: mzp-t-dark
