status: deprecated
context:
  class: mzp-has-aspect-16-9
  image: /img/image-16-9.jpg
  title: Feature Card title with about 40-50 characters
  desc: A description of about 150 characters, give or take. That means we usually only have room for one or two sentences. Here is what that looks like.
  cta: Call to action
  cta_link: https://example.com
variants:
  - name: Left Half
    notes: |
      Add the class `mzp-l-card-feature-left-half` to arrange the text on the left side, half the width of the container.

      **This variant is deprecated.**  Use [Split](/components/detail/split--default) instead.
    context:
      class: mzp-l-card-feature-left-half mzp-has-aspect-3-2
      image: /img/image-3-2.jpg
  - name: Right Half
    notes: |
      Add the class `mzp-l-card-feature-right-half` to arrange the text on the right side, half the width of the container.

      **This variant is deprecated.** Use [Split](/components/detail/split--reversed) instead.
    context:
      class: mzp-l-card-feature-right-half mzp-has-aspect-3-2
      image: /img/image-3-2.jpg
  - name: Left Third
    notes: |
      Add the class `mzp-l-card-feature-left-half` to arrange the text on the left side, one third the width of the container.

      **This variant is deprecated.** Use [Split](/components/detail/split--narrow-body) instead.
    context:
      class: mzp-l-card-feature-left-third mzp-has-aspect-3-2
      image: /img/image-3-2.jpg
  - name: Right Third
    notes: |
      Add the class `mzp-l-card-feature-right-third` to arrange the text on the right side, one third the width of the container.

      **This variant is deprecated.** Use [Split](/components/detail/split--narrow-body) instead.
    context:
      class: mzp-l-card-feature-right-third mzp-has-aspect-3-2
      image: /img/image-3-2.jpg
