context:
  label: Label
  name: name
  id: select
  options:
    - text: Option 1
      value: 1
    - text: Option 2
      value: 2
    - text: Option 3
      value: 3
  msg: Error message
  info: Optional additional information
