preview: '@preview-unpadded'
context:
  layout: start
variants:
  - name: Sidebar End
    context:
      layout: end
    notes: |
      This example uses `mzp-l-sidebar-end` layout class. The sidebar will appear on the right in left-to-right (LTR) languages and on the left in right-to-left (RTL) languages.

      Colored borders are for demonstration only. They are not part of the component styles.
